services:
  dev-db:
    image: mongo:latest
    container_name: dev-db
    ports:
      - "27017:27017"
    volumes:
      - dev-db-data:/data/db
    networks:
      - testing-network
    restart: always

volumes:
  dev-db-data:
  int-db-data:

networks:
  testing-network:
    driver: bridge